import type { NextPage } from "next";
import Head from "next/head";
import { useAppDispatch, useAppSelector } from "hooks";
import { logout } from "@app/redux/slices/UserSlice";
import { successNotification } from "ultis/notification";
import { useRouter } from "next/router";
import { listUser } from "api/User/ApiUser";
import { useQuery } from "react-query";

const Home: NextPage = () => {
  const user = useAppSelector((state) => state.user);

  const router = useRouter();

  const dispatch = useAppDispatch();

  const hanldeLogout = () => {
    dispatch(logout());
    successNotification("Logout");
    router.push("/auth/login");
  };

  const dataListUser = useQuery("list-user", listUser);

  console.log(dataListUser.data);

  return (
    <div className="home">
      <Head>
        <title>Base App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Base App</h1>

      <button onClick={hanldeLogout}>Logout</button>
      <button onClick={() => console.log(user)}>Log</button>
    </div>
  );
};

export default Home;
